services:
  - type: web
    name: bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: TOKEN
        sync: false
